import type { Metadata } from "next";
import { Commissioner } from "next/font/google";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import "./globals.css";





const commissioner = Commissioner({
  variable: "--font-commissioner",
  subsets: ["latin"],
  weight: ["400", "500", "700"], // Include all weights
});




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${commissioner.variable} antialiased`}
      >
       <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
